/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Fabian Navarro
 */
public class VentanaRegistroReservas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistroReservas
     */
    public VentanaRegistroReservas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbHI = new javax.swing.JLabel();
    lbHF = new javax.swing.JLabel();
    lbCantP = new javax.swing.JLabel();
    lbRec = new javax.swing.JLabel();
    txtRecursoPrimario = new javax.swing.JTextField();
    txtCantPersonas = new javax.swing.JTextField();
    txtHoraIni = new javax.swing.JTextField();
    txtHoraFin = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaBusAvan = new javax.swing.JTable();
    btBuscar = new javax.swing.JButton();
    txtIdSala = new javax.swing.JTextField();
    lbIdSala = new javax.swing.JLabel();
    btAtras = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    tablaSalas = new javax.swing.JTable();
    btBusquedaAvanzada = new javax.swing.JButton();
    txtNU = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    lbTema = new javax.swing.JLabel();
    txtTema = new javax.swing.JTextField();
    lbIRes = new javax.swing.JLabel();
    txtIdReserva = new javax.swing.JTextField();
    btCrearReserva = new javax.swing.JButton();
    lbParticipantes = new javax.swing.JLabel();
    lbPN = new javax.swing.JLabel();
    lbPA = new javax.swing.JLabel();
    lbCorreo = new javax.swing.JLabel();
    txtPriNombre = new javax.swing.JTextField();
    txtPriApe = new javax.swing.JTextField();
    txtCorreo = new javax.swing.JTextField();
    btAddParticipante = new javax.swing.JButton();
    txtCapacidadSala = new javax.swing.JTextField();
    lbCapcidad = new javax.swing.JLabel();
    txtLugar = new javax.swing.JTextField();
    lbLugar = new javax.swing.JLabel();
    txtCedula = new javax.swing.JTextField();
    lbCedula = new javax.swing.JLabel();
    lbCarnet = new javax.swing.JLabel();
    txtCarnet = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lbHI.setText("Hora Inicio:");

    lbHF.setText("Hora Finalización:");

    lbCantP.setText("Cantidad Personas:");

    lbRec.setText("Recurso principal requerido:");

    tablaBusAvan.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "identificador", "", "capacidad"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tablaBusAvan.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaBusAvanMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tablaBusAvan);
    if (tablaBusAvan.getColumnModel().getColumnCount() > 0) {
      tablaBusAvan.getColumnModel().getColumn(0).setResizable(false);
      tablaBusAvan.getColumnModel().getColumn(1).setResizable(false);
      tablaBusAvan.getColumnModel().getColumn(2).setResizable(false);
    }

    btBuscar.setText("Buscar");

    lbIdSala.setText("idSala:");

    btAtras.setText("Atrás");

    tablaSalas.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "identificador"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tablaSalas.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaSalasMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tablaSalas);
    if (tablaSalas.getColumnModel().getColumnCount() > 0) {
      tablaSalas.getColumnModel().getColumn(0).setResizable(false);
    }

    btBusquedaAvanzada.setText("Búsqueda Avanzada");
    btBusquedaAvanzada.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btBusquedaAvanzadaActionPerformed(evt);
      }
    });

    jLabel1.setText("Usuario:");

    lbTema.setText("Tema:");

    lbIRes.setText("idReserva:");

    btCrearReserva.setText("Crear Reserva");

    lbParticipantes.setText("Participantes:");

    lbPN.setText("Primer Nombre:");

    lbPA.setText("Primer Apellido:");

    lbCorreo.setText("Correo:");

    btAddParticipante.setText("Añadir Participante");

    lbCapcidad.setText("Capacidad:");

    lbLugar.setText("Lugar:");

    lbCedula.setText("Cédula:");

    lbCarnet.setText("Carnet:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lbTema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lbLugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLugar)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(lbIRes)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(btCrearReserva)
                  .addGap(12, 12, 12))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRec)
                    .addComponent(lbCantP)
                    .addComponent(btBusquedaAvanzada))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCantPersonas)
                    .addComponent(txtRecursoPrimario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                  .addComponent(lbCapcidad)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtCapacidadSala, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(133, 133, 133)))
              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(lbPA)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPriApe, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(lbPN)
                    .addGap(27, 27, 27)
                    .addComponent(txtPriNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(lbCorreo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(btAddParticipante)))))
              .addComponent(lbParticipantes))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAtras))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                  .addComponent(btBuscar)
                  .addGap(18, 18, 18)
                  .addComponent(lbIdSala)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtIdSala, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHF)
                    .addComponent(lbHI))
                  .addGap(8, 8, 8)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHoraFin, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(txtHoraIni))))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNU, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lbCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbCarnet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1)
          .addComponent(lbCedula)
          .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbCarnet)
          .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbHI)
              .addComponent(txtHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbHF)
              .addComponent(txtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btBuscar)
              .addComponent(lbIdSala)
              .addComponent(txtIdSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(5, 5, 5)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lbCantP)
              .addComponent(txtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbRec)
              .addComponent(txtRecursoPrimario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btBusquedaAvanzada)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(8, 8, 8)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtCapacidadSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lbCapcidad)
              .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lbLugar))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbIRes)
              .addComponent(txtIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btCrearReserva)))
          .addGroup(layout.createSequentialGroup()
            .addGap(46, 46, 46)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbTema)
              .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(18, 18, 18)
        .addComponent(lbParticipantes)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbPN)
          .addComponent(txtPriNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbPA)
          .addComponent(txtPriApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbCorreo)
          .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btAddParticipante)
          .addComponent(btAtras))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void tablaBusAvanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBusAvanMouseClicked

    }//GEN-LAST:event_tablaBusAvanMouseClicked

    private void tablaSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalasMouseClicked
        int seleccion = tablaSalas.rowAtPoint(evt.getPoint());
        txtIdSala.setText(String.valueOf(tablaSalas.getValueAt(seleccion, 0)));
    }//GEN-LAST:event_tablaSalasMouseClicked

    private void btBusquedaAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBusquedaAvanzadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBusquedaAvanzadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroReservas().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btAddParticipante;
  public javax.swing.JButton btAtras;
  public javax.swing.JButton btBuscar;
  public javax.swing.JButton btBusquedaAvanzada;
  public javax.swing.JButton btCrearReserva;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel lbCantP;
  private javax.swing.JLabel lbCapcidad;
  private javax.swing.JLabel lbCarnet;
  private javax.swing.JLabel lbCedula;
  private javax.swing.JLabel lbCorreo;
  private javax.swing.JLabel lbHF;
  private javax.swing.JLabel lbHI;
  private javax.swing.JLabel lbIRes;
  private javax.swing.JLabel lbIdSala;
  private javax.swing.JLabel lbLugar;
  private javax.swing.JLabel lbPA;
  private javax.swing.JLabel lbPN;
  private javax.swing.JLabel lbParticipantes;
  private javax.swing.JLabel lbRec;
  private javax.swing.JLabel lbTema;
  public javax.swing.JTable tablaBusAvan;
  public javax.swing.JTable tablaSalas;
  public javax.swing.JTextField txtCantPersonas;
  public javax.swing.JTextField txtCapacidadSala;
  public javax.swing.JTextField txtCarnet;
  public javax.swing.JTextField txtCedula;
  public javax.swing.JTextField txtCorreo;
  public javax.swing.JTextField txtHoraFin;
  public javax.swing.JTextField txtHoraIni;
  public javax.swing.JTextField txtIdReserva;
  public javax.swing.JTextField txtIdSala;
  public javax.swing.JTextField txtLugar;
  public javax.swing.JTextField txtNU;
  public javax.swing.JTextField txtPriApe;
  public javax.swing.JTextField txtPriNombre;
  public javax.swing.JTextField txtRecursoPrimario;
  public javax.swing.JTextField txtTema;
  // End of variables declaration//GEN-END:variables

    public void cerrarVentana() {
        this.dispose();
    }

    public boolean validarDatos() {
        return !( txtHoraIni.getText().equals("") || txtHoraFin.getText().equals("") );
    }

    public boolean validarDatosCompletos() {
        return !( txtIdSala.getText().equals("") || txtCantPersonas.getText().equals("") || txtRecursoPrimario.getText().equals("") );
    }
    
    public boolean validarDatosReserva() {
        return !( txtLugar.getText().equals("") || txtHoraIni.getText().equals("") || txtHoraFin.getText().equals("") || txtCedula.getText().equals("") || txtCantPersonas.getText().equals("") || txtIdSala.getText().equals("") || txtIdReserva.getText().equals("") || txtTema.getText().equals(""));
    }
    
    public boolean validarDatosParticipante() {
        return !(txtPriApe.getText().equals("") || txtPriNombre.getText().equals("") || txtCorreo.getText().equals(""));
    }
}
