/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Fabian Navarro
 */
public class VentanaModificarSala extends javax.swing.JFrame {

    /**
     * Creates new form VentanaModificarEstudiante
     */
    public VentanaModificarSala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbSeleccion = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaSalas = new javax.swing.JTable();
    btVerSalas = new javax.swing.JButton();
    lbModUb = new javax.swing.JLabel();
    txtUbicacion = new javax.swing.JTextField();
    lbModEst = new javax.swing.JLabel();
    txtEstado = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    tablaRecursos = new javax.swing.JTable();
    lbIdRecurso = new javax.swing.JLabel();
    lbNombre = new javax.swing.JLabel();
    lbCantidad = new javax.swing.JLabel();
    txtIdRecurso = new javax.swing.JTextField();
    txtNombre = new javax.swing.JTextField();
    txtCant = new javax.swing.JTextField();
    lbModCant = new javax.swing.JLabel();
    txtModCant = new javax.swing.JTextField();
    btModificarCantRec = new javax.swing.JButton();
    btAgregarRecurso = new javax.swing.JButton();
    btEliminarRecurso = new javax.swing.JButton();
    btRegresar = new javax.swing.JButton();
    lbIdSala = new javax.swing.JLabel();
    txtIdSala = new javax.swing.JTextField();
    btModificarEst = new javax.swing.JButton();
    btVerRecursos = new javax.swing.JButton();
    btModificarUbi = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lbSeleccion.setText("Seleccione una sala:");

    tablaSalas.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "idSala", "Ubicacion", "Capacidad", "idEstado", "idHorario"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tablaSalas.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaSalasMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tablaSalas);
    if (tablaSalas.getColumnModel().getColumnCount() > 0) {
      tablaSalas.getColumnModel().getColumn(0).setResizable(false);
      tablaSalas.getColumnModel().getColumn(1).setResizable(false);
      tablaSalas.getColumnModel().getColumn(2).setResizable(false);
      tablaSalas.getColumnModel().getColumn(3).setResizable(false);
      tablaSalas.getColumnModel().getColumn(4).setResizable(false);
    }

    btVerSalas.setText("Ver salas");

    lbModUb.setText("Modificar Ubicación:");

    lbModEst.setText("Modificar Estado:");

    jLabel4.setText("Modificar Recursos:");

    tablaRecursos.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "idRecurso", "detalle", "cantidad"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tablaRecursos.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaRecursosMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tablaRecursos);
    if (tablaRecursos.getColumnModel().getColumnCount() > 0) {
      tablaRecursos.getColumnModel().getColumn(0).setResizable(false);
      tablaRecursos.getColumnModel().getColumn(1).setResizable(false);
      tablaRecursos.getColumnModel().getColumn(2).setResizable(false);
    }

    lbIdRecurso.setText("IdRecurso:");

    lbNombre.setText("Nombre:");

    lbCantidad.setText("Cantidad:");

    lbModCant.setText("Modificar Cantidad:");

    btModificarCantRec.setText("Modificar Cantidad");

    btAgregarRecurso.setText("Agregar Recurso");

    btEliminarRecurso.setText("Eliminar Recurso");

    btRegresar.setText("Regresar");

    lbIdSala.setText("idSala:");

    btModificarEst.setText("Modificar Estado");

    btVerRecursos.setText("Ver recursos");

    btModificarUbi.setText("Modificar Ubicación");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(42, 42, 42)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(btRegresar)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel4)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btVerRecursos))
                .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                      .addComponent(lbCantidad)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(90, 90, 90)
                  .addComponent(lbNombre)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(txtUbicacion)
                  .addComponent(btModificarUbi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(119, 119, 119)
                    .addComponent(lbModEst))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(btModificarEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(txtEstado)))))
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(layout.createSequentialGroup()
                  .addComponent(lbIdSala)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtIdSala))
                .addGroup(layout.createSequentialGroup()
                  .addComponent(lbModUb)
                  .addGap(163, 163, 163)))
              .addComponent(lbIdRecurso)
              .addGroup(layout.createSequentialGroup()
                .addComponent(lbModCant)
                .addGap(18, 18, 18)
                .addComponent(txtModCant, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btModificarCantRec))
              .addGroup(layout.createSequentialGroup()
                .addComponent(btAgregarRecurso)
                .addGap(32, 32, 32)
                .addComponent(btEliminarRecurso))
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                  .addComponent(lbSeleccion)
                  .addGap(263, 263, 263)
                  .addComponent(btVerSalas))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(32, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btVerSalas)
          .addComponent(lbSeleccion))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(94, 94, 94)
            .addComponent(btModificarUbi)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(btVerRecursos)))
          .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbIdSala)
              .addComponent(txtIdSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbModUb)
              .addComponent(lbModEst))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btModificarEst)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbIdRecurso)
          .addComponent(lbNombre)
          .addComponent(txtIdRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbCantidad)
          .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(17, 17, 17)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbModCant)
          .addComponent(txtModCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btModificarCantRec))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btEliminarRecurso)
          .addComponent(btAgregarRecurso)
          .addComponent(btRegresar))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void tablaSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalasMouseClicked
        int seleccion = tablaSalas.rowAtPoint(evt.getPoint());
        txtIdSala.setText(String.valueOf(tablaSalas.getValueAt(seleccion, 0)));
    }//GEN-LAST:event_tablaSalasMouseClicked

    private void tablaRecursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRecursosMouseClicked
        int seleccion = tablaRecursos.rowAtPoint(evt.getPoint());
        txtIdRecurso.setText(String.valueOf(tablaRecursos.getValueAt(seleccion, 0)));
        txtNombre.setText(String.valueOf(tablaRecursos.getValueAt(seleccion, 1)));
        txtCant.setText(String.valueOf(tablaRecursos.getValueAt(seleccion, 2)));
    }//GEN-LAST:event_tablaRecursosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificarSala().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btAgregarRecurso;
  public javax.swing.JButton btEliminarRecurso;
  public javax.swing.JButton btModificarCantRec;
  public javax.swing.JButton btModificarEst;
  public javax.swing.JButton btModificarUbi;
  public javax.swing.JButton btRegresar;
  public javax.swing.JButton btVerRecursos;
  public javax.swing.JButton btVerSalas;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel lbCantidad;
  private javax.swing.JLabel lbIdRecurso;
  private javax.swing.JLabel lbIdSala;
  private javax.swing.JLabel lbModCant;
  private javax.swing.JLabel lbModEst;
  private javax.swing.JLabel lbModUb;
  private javax.swing.JLabel lbNombre;
  private javax.swing.JLabel lbSeleccion;
  public javax.swing.JTable tablaRecursos;
  public javax.swing.JTable tablaSalas;
  public javax.swing.JTextField txtCant;
  public javax.swing.JTextField txtEstado;
  public javax.swing.JTextField txtIdRecurso;
  public javax.swing.JTextField txtIdSala;
  public javax.swing.JTextField txtModCant;
  public javax.swing.JTextField txtNombre;
  public javax.swing.JTextField txtUbicacion;
  // End of variables declaration//GEN-END:variables
  public void cerrarVentana() {
        this.dispose();
    }

    public void limpiarCamposModificacionesSala() {
        txtEstado.setText("");
        txtUbicacion.setText("");
    }

    public void limpiarCamposRecurso() {
        txtCant.setText("");
        txtIdRecurso.setText("");
        txtModCant.setText("");
        txtNombre.setText("");
    }

}
