/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.ConexionJavaMySQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Fabian Navarro
 */
public class VentanaRegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaRegistroUsuario() {
        initComponents();
        PreparedStatement ps = null;
        ResultSet rs = null;
        ConexionJavaMySQL conn = new ConexionJavaMySQL();
        Connection con = conn.getConexion();

        try {

            String sql = "SELECT * FROM Rol";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                cbxRol.addItem(rs.getString("idRol"));
            }
            rs.close();
        } catch (SQLException ex) {
            System.err.println("Error consulta :" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbAddUser = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaPersona = new javax.swing.JTable();
    lbUser = new javax.swing.JLabel();
    lbPass = new javax.swing.JLabel();
    lbEstado = new javax.swing.JLabel();
    btAddUser = new javax.swing.JButton();
    txtUser = new javax.swing.JTextField();
    txtPass = new javax.swing.JTextField();
    txtId = new javax.swing.JTextField();
    lbID = new javax.swing.JLabel();
    btOpciones = new javax.swing.JButton();
    cbxRol = new javax.swing.JComboBox<>();
    lbRol = new javax.swing.JLabel();
    btUpdate = new javax.swing.JButton();
    cbxEstado = new javax.swing.JComboBox<>();
    btSalir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lbAddUser.setText("Agregar Usuario");

    tablaPersona.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Cédula", "PrimerNombre", "PrimerApellido", "Correo", "Teléfono"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tablaPersona.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaPersonaMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tablaPersona);
    if (tablaPersona.getColumnModel().getColumnCount() > 0) {
      tablaPersona.getColumnModel().getColumn(0).setResizable(false);
      tablaPersona.getColumnModel().getColumn(1).setResizable(false);
      tablaPersona.getColumnModel().getColumn(2).setResizable(false);
      tablaPersona.getColumnModel().getColumn(3).setResizable(false);
      tablaPersona.getColumnModel().getColumn(4).setResizable(false);
    }

    lbUser.setText("Nombre de usuario:");

    lbPass.setText("Contraseña:");

    lbEstado.setText("Estado:");

    btAddUser.setText("Añadir Usuario");

    lbID.setText("ID:");

    btOpciones.setText("Opciones");

    cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

    lbRol.setText("Rol:");

    btUpdate.setText("Actualizar");

    cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activado", "Desactivado" }));

    btSalir.setText("Salir");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btUpdate)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
              .addGap(247, 247, 247)
              .addComponent(lbAddUser))
            .addGroup(layout.createSequentialGroup()
              .addGap(105, 105, 105)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btAddUser)
                .addGroup(layout.createSequentialGroup()
                  .addGap(11, 11, 11)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUser)
                    .addGroup(layout.createSequentialGroup()
                      .addComponent(lbID)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addGroup(layout.createSequentialGroup()
                        .addComponent(btOpciones)
                        .addGap(52, 52, 52)
                        .addComponent(btSalir)
                        .addGap(14, 14, 14))
                      .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addComponent(lbRol)
                          .addComponent(lbPass)
                          .addComponent(lbEstado))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbxRol, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))))
        .addContainerGap(121, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(lbAddUser)
        .addGap(18, 18, 18)
        .addComponent(btUpdate)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbID))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lbUser)
          .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lbPass)
          .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbEstado)
          .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(21, 21, 21)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbRol))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btAddUser)
          .addComponent(btOpciones)
          .addComponent(btSalir))
        .addGap(23, 23, 23))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void tablaPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPersonaMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ConexionJavaMySQL objCon = new ConexionJavaMySQL();
            Connection conn = objCon.getConexion();

            int Fila = tablaPersona.getSelectedRow();
            String cedula = tablaPersona.getValueAt(Fila, 0).toString();

            ps = conn.prepareStatement("SELECT cedula, primerNombre, primerApellido FROM Persona WHERE cedula=?");
            ps.setString(1, cedula);
            rs = ps.executeQuery();

            while (rs.next()) {
                txtId.setText(rs.getString("cedula"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_tablaPersonaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroUsuario().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btAddUser;
  public javax.swing.JButton btOpciones;
  public javax.swing.JButton btSalir;
  public javax.swing.JButton btUpdate;
  public javax.swing.JComboBox<String> cbxEstado;
  public javax.swing.JComboBox<String> cbxRol;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lbAddUser;
  private javax.swing.JLabel lbEstado;
  private javax.swing.JLabel lbID;
  private javax.swing.JLabel lbPass;
  private javax.swing.JLabel lbRol;
  private javax.swing.JLabel lbUser;
  public javax.swing.JTable tablaPersona;
  public javax.swing.JTextField txtId;
  public javax.swing.JTextField txtPass;
  public javax.swing.JTextField txtUser;
  // End of variables declaration//GEN-END:variables
    public boolean validarDatos() {
        if (txtId.getText().equals("") || txtUser.getText().equals("") || txtPass.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    public void cerrarVentana() {
        this.dispose();
    }

    public void limpiarCampos() {
        txtId.setText("");
        txtUser.setText("");
        txtPass.setText("");
    }
}
