/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Fabian Navarro
 */
public class VentanaAgregarSala extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAgregarSala
     */
    public VentanaAgregarSala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbIdentificador = new javax.swing.JLabel();
    lbUbicacion = new javax.swing.JLabel();
    lbCapacidad = new javax.swing.JLabel();
    lbEstado = new javax.swing.JLabel();
    txtIdentificador = new javax.swing.JTextField();
    txtUbicacion = new javax.swing.JTextField();
    txtCapacidad = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaHorarios = new javax.swing.JTable();
    btAgregar = new javax.swing.JButton();
    btSalir = new javax.swing.JButton();
    cbxEstado = new javax.swing.JComboBox<>();
    btHorarios = new javax.swing.JButton();
    txtIdRecurso = new javax.swing.JTextField();
    lbIdRecurso = new javax.swing.JLabel();
    lbNombre = new javax.swing.JLabel();
    lbCantidad = new javax.swing.JLabel();
    txtNombreRec = new javax.swing.JTextField();
    txtCantidad = new javax.swing.JTextField();
    btAgregarRecurso = new javax.swing.JButton();
    lbRecurso = new javax.swing.JLabel();
    txtIdHorario = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lbIdentificador.setText("Identificador:");

    lbUbicacion.setText("Ubicación:");

    lbCapacidad.setText("Capacidad:");

    lbEstado.setText("Estado:");

    tablaHorarios.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "idHorario", "nombreHorario", "diasDisponible", "horaApertura", "horaCierre"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tablaHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaHorariosMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tablaHorarios);
    if (tablaHorarios.getColumnModel().getColumnCount() > 0) {
      tablaHorarios.getColumnModel().getColumn(0).setResizable(false);
      tablaHorarios.getColumnModel().getColumn(1).setResizable(false);
      tablaHorarios.getColumnModel().getColumn(2).setResizable(false);
      tablaHorarios.getColumnModel().getColumn(3).setResizable(false);
      tablaHorarios.getColumnModel().getColumn(4).setResizable(false);
    }

    btAgregar.setText("Agregar");

    btSalir.setText("Regresar");

    cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activa", "Inactiva", "Mantenimiento" }));

    btHorarios.setText("Ver Horarios");

    lbIdRecurso.setText("idRecurso:");

    lbNombre.setText("Nombre:");

    lbCantidad.setText("Cantidad:");

    btAgregarRecurso.setText("Agregar Recurso");

    lbRecurso.setText("Recurso:");

    jLabel1.setText("idHorario:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(53, 53, 53)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btSalir)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(lbIdentificador)
                      .addComponent(lbUbicacion)
                      .addComponent(lbCapacidad))
                    .addGap(49, 49, 49)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addComponent(lbEstado))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lbNombre)
                  .addComponent(lbIdRecurso)
                  .addComponent(lbCantidad)
                  .addComponent(lbRecurso)))
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                  .addComponent(btAgregar)
                  .addGap(251, 251, 251))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(btHorarios)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(txtIdHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(txtNombreRec, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btAgregarRecurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(txtIdRecurso))))
        .addGap(0, 36, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(42, 42, 42)
            .addComponent(lbRecurso)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbIdRecurso)
              .addComponent(txtIdRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtNombreRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lbNombre))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lbCantidad)))
          .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbIdentificador)
              .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbUbicacion)
              .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(22, 22, 22)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbCapacidad)
              .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lbEstado)
              .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btHorarios)
            .addGap(15, 15, 15)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtIdHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
            .addComponent(btAgregar))
          .addGroup(layout.createSequentialGroup()
            .addComponent(btAgregarRecurso)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void tablaHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHorariosMouseClicked
        int seleccion = tablaHorarios.rowAtPoint(evt.getPoint());
        txtIdHorario.setText(String.valueOf(tablaHorarios.getValueAt(seleccion, 0)));
    }//GEN-LAST:event_tablaHorariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarSala().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btAgregar;
  public javax.swing.JButton btAgregarRecurso;
  public javax.swing.JButton btHorarios;
  public javax.swing.JButton btSalir;
  public javax.swing.JComboBox<String> cbxEstado;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lbCantidad;
  private javax.swing.JLabel lbCapacidad;
  private javax.swing.JLabel lbEstado;
  private javax.swing.JLabel lbIdRecurso;
  private javax.swing.JLabel lbIdentificador;
  private javax.swing.JLabel lbNombre;
  private javax.swing.JLabel lbRecurso;
  private javax.swing.JLabel lbUbicacion;
  public javax.swing.JTable tablaHorarios;
  public javax.swing.JTextField txtCantidad;
  public javax.swing.JTextField txtCapacidad;
  public javax.swing.JTextField txtIdHorario;
  public javax.swing.JTextField txtIdRecurso;
  public javax.swing.JTextField txtIdentificador;
  public javax.swing.JTextField txtNombreRec;
  public javax.swing.JTextField txtUbicacion;
  // End of variables declaration//GEN-END:variables
public void cerrarVentana() {
        this.dispose();
    }

    public void limpiarCamposSala() {
        txtCapacidad.setText("");
        txtUbicacion.setText("");
    }

    public void limpiarCamposRecurso() {
        txtIdRecurso.setText("");
        txtNombreRec.setText("");
        txtCantidad.setText("");
    }

    public boolean validarDatosSala() {
        return !(txtCapacidad.getText().equals("")
                || txtIdentificador.getText().equals("") || txtUbicacion.getText().equals(""));
    }

    public boolean validarDatosRecurso() {
        return !(txtIdRecurso.getText().equals("") || txtNombreRec.getText().equals("") || txtCantidad.getText().equals(""));
    }

}
